apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-website-deployment
  labels:
    app: abc-website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abc-website
  template:
    metadata:
      labels:
        app: abc-website
    spec:
        containers:
        - name: abc-website
          image: abc-corporate-website:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
